apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freds-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freds
  labels:
    app: freds
spec:
  replicas: 1
  template:
    metadata:
      name: freds
      labels:
        app: freds
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: freds
        image: akssandbox64150903.azurecr.io/freds:latest
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: "c:\\InetPub\\freds"
          name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: freds-disk
  selector:
    matchLabels:
      app: freds
---
apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: sample
